### ISSUE TITLE
Failing to create new setting

### ISSUE THREAD

**Issue by alcoranpaul** [alcoranpaul/DunGen#49]
```csharp
[ 00:24:47.074 ]: [Error] Missing file 'E:\Projects/Game Dev/Flax/TestDunGen/Plugins/DunGen/Content/Data/DunGenSettings.json'
[ 00:24:47.075 ]: [Warning] Failed to load settings @ E:\Projects/Game Dev/Flax/TestDunGen\Plugins\DunGen\Content\Data\DunGenSettings.json 
[ 00:24:47.076 ]: [Warning] Debug Material Path does not exist @ E:\Projects/Game Dev/Flax/TestDunGen\Plugins\DunGen\Content\Debugging\Debug\Material
[ 00:24:47.076 ]: [Warning] Debug Prefab Path does not exist @ E:\Projects/Game Dev/Flax/TestDunGen\Plugins\DunGen\Content\Debugging\Debug\Prefabs
[ 00:24:47.078 ]: [Warning] Exception has been thrown during Window.OnMouseUp. Could not find a part of the path 'E:\Projects\Game Dev\Flax\TestDunGen\Plugins\DunGen\Content\Debugging\Debug\Material'.
Stack strace:
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.Directory.GetFiles(String path, String searchPattern, EnumerationOptions enumerationOptions)
   at DunGenEditor.DunGenWindow.GetDebugSettings() in E:\Projects\Game Dev\Flax\TestDunGen\Plugins\DunGen\Source\DunGenEditor\DunGenWindow.cs:line 363
   at DunGenEditor.DunGenWindow.CreateSettings() in E:\Projects\Game Dev\Flax\TestDunGen\Plugins\DunGen\Source\DunGenEditor\DunGenWindow.cs:line 332
   at DunGenEditor.DunGenWindow.OpenData() in E:\Projects\Game Dev\Flax\TestDunGen\Plugins\DunGen\Source\DunGenEditor\DunGenWindow.cs:line 315
   at FlaxEngine.GUI.Button.OnClick() in D:\a\FlaxEngine\FlaxEngine\Source\Engine\UI\GUI\Common\Button.cs:line 149
   at FlaxEngine.GUI.Button.OnMouseUp(Float2 location, MouseButton button) in D:\a\FlaxEngine\FlaxEngine\Source\Engine\UI\GUI\Common\Button.cs:line 276
   at FlaxEngine.GUI.ContainerControl.OnMouseUp(Float2 location, MouseButton button) in D:\a\FlaxEngine\FlaxEngine\Source\Engine\UI\GUI\ContainerControl.cs:line 1029
   at FlaxEngine.GUI.ContainerControl.OnMouseUp(Float2 location, MouseButton button) in D:\a\FlaxEngine\FlaxEngine\Source\Engine\UI\GUI\ContainerControl.cs:line 1029
   at FlaxEditor.GUI.Docking.DockPanelProxy.OnMouseUp(Float2 location, MouseButton button) in D:\a\FlaxEngine\FlaxEngine\Source\Editor\GUI\Docking\DockPanelProxy.cs:line 424
   at FlaxEngine.GUI.ContainerControl.OnMouseUp(Float2 location, MouseButton button) in D:\a\FlaxEngine\FlaxEngine\Source\Engine\UI\GUI\ContainerControl.cs:line 1029
   at FlaxEngine.GUI.ContainerControl.OnMouseUp(Float2 location, MouseButton button) in D:\a\FlaxEngine\FlaxEngine\Source\Engine\UI\GUI\ContainerControl.cs:line 1029
   at FlaxEngine.GUI.ContainerControl.OnMouseUp(Float2 location, MouseButton button) in D:\a\FlaxEngine\FlaxEngine\Source\Engine\UI\GUI\ContainerControl.cs:line 1029
   at FlaxEngine.GUI.ContainerControl.OnMouseUp(Float2 location, MouseButton button) in D:\a\FlaxEngine\FlaxEngine\Source\Engine\UI\GUI\ContainerControl.cs:line 1029
   at FlaxEngine.GUI.ContainerControl.OnMouseUp(Float2 location, MouseButton button) in D:\a\FlaxEngine\FlaxEngine\Source\Engine\UI\GUI\ContainerControl.cs:line 1029
   at FlaxEngine.Window.Internal_OnMouseUp(Float2& mousePos, MouseButton button) in D:\a\FlaxEngine\FlaxEngine\Source\Engine\Platform\Window.cs:line 242
   at FlaxEngine.Interop.NativeInterop.Invoker.InvokerNoRet2`3.MarshalAndInvoke(Object delegateContext, ManagedHandle instancePtr, IntPtr paramPtr) in D:\a\FlaxEngine\FlaxEngine\Source\Engine\Engine\NativeInterop.Invoker.cs:line 387
   at FlaxEngine.Interop.NativeInterop.InvokeMethod(ManagedHandle instanceHandle, ManagedHandle methodHandle, IntPtr paramPtr, IntPtr exceptionPtr) in D:\a\FlaxEngine\FlaxEngine\Source\Engine\Engine\NativeInterop.Unmanaged.cs:line 806
[ 00:24:47.078 ]: [Error] Exception has been thrown during Window.OnMouseUp.
Could not find a part of the path 'E:\Projects\Game Dev\Flax\TestDunGen\Plugins\DunGen\Content\Debugging\Debug\Material'.
```
Line:
https://github.com/alcoranpaul/DunGen/blob/3faea47c733a974b0809a0258d101c406880c6e2/Source/DunGenEditor/DunGenWindow.cs#L347-L358

**Comment by alcoranpaul** [comment]
change 
https://github.com/alcoranpaul/DunGen/blob/3faea47c733a974b0809a0258d101c406880c6e2/Source/DunGenEditor/DunGenEditor.cs#L30

into
```csharp
return Path.Combine(Globals.ProjectFolder, "Plugins", "DunGen", "Content", DEBUG_PREFAB_FOLDER);
```
